### ISSUE TITLE
Gradle build 8.1.2 build error in android

### ISSUE THREAD

**Issue by phamhuudat** [programmierbar/lottie_native#6]
<img width="1816" alt="Screenshot 2023-12-20 at 10 07 17" src="https://github.com/programmierbar/lottie_native/assets/16275293/d0dddcc9-0a02-47ed-96ab-559db2f5b3b1">

**Comment by phamhuudat** [comment]
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by blaugold** [comment]
I've just published `lottie_native` `0.1.1` which support AGP 8.0.0.
